### ISSUE TITLE
Unable to run in Bitwig 4.3 Beta 6

### ISSUE THREAD

**Issue by furioncycle** [schwaaa/clap-imgui#2]
Tried to build the plugins following the README and was not able to see the plugins come up in my daw.

DAW: Bitwig 4.3 Beta 6
OS: Arch flavor linux 

Build had no warnings/errors

**Comment by voidshine** [comment]
I encountered the same problem using Bitwig 4.3 Stable -- CLAP support itself was fine (Dexed.clap worked great) but this plugin was broken for Bitwig until I updated src/clap/ in PR linked above.
